#if UNITY_EDITOR
using System;
using System.Linq;
using System.Text;
using System.IO;
using System.Reflection;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using MessagePipe;
using EventSys.Interface;

namespace EventSys.Editor
{
    [InitializeOnLoad]
    internal static class EventBrokerCodeGen
    {
        // 產碼輸出路徑（可自行調整）
        private const string OutputDir = "Assets/Main/SnoweveToolKit/EventSys/Generated";
        private const string OutputFile = OutputDir + "/EventBrokerRegistration.generated.cs";

        static EventBrokerCodeGen() {
            // 在每次 domain reload/腳本重載後排程檢查一次
            EditorApplication.delayCall += EnsureGeneratedUpToDate;
        }

        [MenuItem("Tools/Event System/Regenerate Event Brokers")]
        private static void MenuRegenerate() => EnsureGeneratedUpToDate(true);

        internal static bool ExistsGeneratedFileOnDisk() => File.Exists(OutputFile);

        /// <summary>
        /// 若產碼缺失時，Editor 模式提供一次反射註冊的保險，避免你 Play 被擋住。
        /// 僅在 Editor 下會被呼叫（Runtime 不包含此方法）。
        /// </summary>
        internal static void FallbackReflectiveRegister(BuiltinContainerBuilder builder) {
            // 僅 Editor 可用，避免 Runtime 反射
            MethodInfo add = typeof(BuiltinContainerBuilder)
                .GetMethods(BindingFlags.Instance | BindingFlags.Public)
                .Single(m => m.Name == "AddMessageBroker"
                             && m.IsGenericMethodDefinition
                             && m.GetGenericArguments().Length == 1
                             && m.GetParameters().Length == 0);

            foreach (Type t in EnumerateEventStructTypes()) {
                add.MakeGenericMethod(t).Invoke(builder, null);
            }

            Debug.LogWarning("[EventSys] 使用 Fallback 反射註冊（僅 Editor）。請重新產生 generated 檔以恢復 0 反射。");
        }

        private static void EnsureGeneratedUpToDate() => EnsureGeneratedUpToDate(false);

        private static void EnsureGeneratedUpToDate(bool forceLog) {
            try {
                Directory.CreateDirectory(OutputDir);

                string code = GenerateSource();
                if (File.Exists(OutputFile)) {
                    string old = File.ReadAllText(OutputFile, new UTF8Encoding(false));
                    if (old == code) {
                        if (forceLog) Debug.Log("[EventSys] EventBrokerRegistration 已是最新。");
                        return; // 無變更，不觸發重編譯
                    }
                }

                File.WriteAllText(OutputFile, code, new UTF8Encoding(false));
                AssetDatabase.ImportAsset(OutputFile);
                if (forceLog) Debug.Log($"[EventSys] 產生：{OutputFile}");
            }
            catch (Exception ex) {
                Debug.LogError($"[EventSys] 產碼失敗：{ex}");
            }
        }

        private static string GenerateSource() {
            string[] types = EnumerateEventStructTypes()
                .Select(t => $"builder.AddMessageBroker<{ToGlobalTypeName(t)}>();")
                .OrderBy(s => s, StringComparer.Ordinal) // 穩定排序，降低 diff
                .ToArray();

            StringBuilder sb = new StringBuilder(1024 + types.Length * 64);
            sb.AppendLine(
                "// <auto-generated> DO NOT EDIT. This file is generated by EventBrokerCodeGen. </auto-generated>");
            sb.AppendLine("#pragma warning disable 1591");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using MessagePipe;");
            sb.AppendLine("namespace EventSys.Runtime");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class MessagePipeInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        static partial void RegisterEventBrokers(BuiltinContainerBuilder builder)");
            sb.AppendLine("        {");
            if (types.Length == 0) {
                sb.AppendLine("            // No IEventData structs found.");
            }
            else {
                foreach (string line in types) sb.AppendLine("            " + line);
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static IEnumerable<Type> EnumerateEventStructTypes() {
            // 使用 TypeCache（快）：抓所有繼承 IEventData 的型別
            // 只收 struct，排除 enum / ref struct / 泛型
            foreach (Type t in TypeCache.GetTypesDerivedFrom<IEventData>()) {
                if (!t.IsValueType) continue;
                if (t.IsEnum) continue;
                if (t.IsGenericType) continue;
#if UNITY_2022_3_OR_NEWER
                if (t.IsByRefLike) continue;
#endif
                yield return t;
            }
        }

        private static string ToGlobalTypeName(Type t) {
            // global::Namespace.TypeName（處理巢狀類型）
            string name = t.FullName!.Replace('+', '.'); // nested type
            return "global::" + name;
        }
    }
}
#endif